CREATE SCHEMA auth;
GO

CREATE TABLE Doctor (
    ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
    Specialization NVARCHAR(50) NOT NULL
);

CREATE TABLE auth.AspNetUsers (
    Id NVARCHAR(450) PRIMARY KEY,
    UserName NVARCHAR(256) NOT NULL,
    NormalizedUserName NVARCHAR(256) NOT NULL,
    Email NVARCHAR(256) NOT NULL,
    NormalizedEmail NVARCHAR(256) NOT NULL,
    EmailConfirmed BIT NOT NULL,
    PasswordHash NVARCHAR(MAX),
    SecurityStamp NVARCHAR(MAX)
);

CREATE TABLE Guardian (
    ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
    UserID NVARCHAR(450) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES auth.AspNetUsers(Id)
);

CREATE TABLE Treatment (
    ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(50) NOT NULL
);

CREATE TABLE Patient (
    ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
    GuardianID UNIQUEIDENTIFIER NOT NULL,
    TreatmentID UNIQUEIDENTIFIER NOT NULL,
    DoctorID UNIQUEIDENTIFIER NOT NULL,
    Avatar NVARCHAR(100),
    FOREIGN KEY (GuardianID) REFERENCES Guardian(ID),
    FOREIGN KEY (TreatmentID) REFERENCES Treatment(ID),
    FOREIGN KEY (DoctorID) REFERENCES Doctor(ID)
);

CREATE TABLE JournalEntry (
    ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PatientID UNIQUEIDENTIFIER NOT NULL,
    GuardianID UNIQUEIDENTIFIER NOT NULL,
    Date DATETIME NOT NULL,
    Content NVARCHAR(MAX) NOT NULL,
    FOREIGN KEY (PatientID) REFERENCES Patient(ID),
    FOREIGN KEY (GuardianID) REFERENCES Guardian(ID)
);

CREATE TABLE Appoinment (
    ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(50) NOT NULL,
    Url NVARCHAR(256),
    Image VARBINARY(MAX),
    DurationInMinutes INT NOT NULL
);

CREATE TABLE Treatment_Appoinment (
    TreatmentID UNIQUEIDENTIFIER NOT NULL,
    AppoinmentID UNIQUEIDENTIFIER NOT NULL,
    Sequence INT NOT NULL,
    PRIMARY KEY (TreatmentID, AppoinmentID),
    FOREIGN KEY (TreatmentID) REFERENCES Treatment(ID),
    FOREIGN KEY (AppoinmentID) REFERENCES Appoinment(ID)
);

CREATE TABLE auth.AspNetRoles (
    Id NVARCHAR(450) PRIMARY KEY,
    Name NVARCHAR(256) NOT NULL,
    NormalizedName NVARCHAR(256) NOT NULL,
    ConcurrencyStamp NVARCHAR(MAX)
);

CREATE TABLE auth.AspNetRoleClaims (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    RoleId NVARCHAR(450) NOT NULL,
    ClaimType NVARCHAR(MAX),
    ClaimValue NVARCHAR(MAX),
    FOREIGN KEY (RoleId) REFERENCES auth.AspNetRoles(Id)
);

CREATE TABLE auth.AspNetUserRoles (
    UserId NVARCHAR(450) NOT NULL,
    RoleId NVARCHAR(450) NOT NULL,
    PRIMARY KEY (UserId, RoleId),
    FOREIGN KEY (UserId) REFERENCES auth.AspNetUsers(Id),
    FOREIGN KEY (RoleId) REFERENCES auth.AspNetRoles(Id)
);
