name: HQB CI/CD Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup .NET
          uses: actions/setup-dotnet@v2
          with:
              dotnet-version: '9.0.x'

        - name: Restore dependencies
          run: dotnet restore

        - name: Build project
          run: dotnet build --configuration Release

        - name: Run tests
          run: dotnet test --configuration Release --no-build --verbosity normal

    deploy:
        runs-on: ubuntu-latest
        needs: build

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup .NET
          uses: actions/setup-dotnet@v2
          with:
              dotnet-version: '9.0.x'

        - name: Publish
          run: dotnet publish HQB.WebApi/HQB.WebApi.csproj --configuration Release --output ./publish

        - name: Deploy to Azure Web App
          uses: azure/webapps-deploy@v2
          with:
              app-name: '${{ secrets.AZURE_WEBAPP_NAME }}'
              publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
              package: ./publish